### ISSUE TITLE
贊助商前台增加logo上傳檔案類型

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#101]
http://prntscr.com/ojzg78
目前測試如圖，logo部分可能有ai檔案類型，但無法上傳
可放寬檔案限制(增加ai,psd,svg,pdf,eps)

**Comment by hashman** [comment]
請 @FWcloud916 幫忙處理，如果在 validator 設定 image 僅可以上傳以下種類檔案

`return $this->validateMimes($attribute, $value, ['jpeg', 'png', 'gif', 'bmp', 'svg']);`

**Comment by kaojane** [comment]
Hi 我又回來了，
考慮可能廠商提供不同長寬比例的logo複數圖檔供選擇
贊助組希望再加入rar與zip兩種壓縮檔類型~再麻煩

**Comment by hashman** [comment]
請 @FWcloud916 抽空幫忙 <(_ _)>

**Comment by hashman** [comment]
推送上去了，請 @kaojane 幫忙看看，謝謝

**Comment by kaojane** [comment]
OK有了 感謝~
