### ISSUE TITLE
贊助商表單重新進入編輯，公司介紹會被洗掉

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#105]
原填好之表單，送出後重新再以url及pw登入後，原本輸入的公司簡介沒有帶入
參考比對
http://prntscr.com/omkjnb
http://prntscr.com/omkk3t

**Comment by hashman** [comment]
請 @Tzuhui 幫忙確認，謝謝

**Comment by hashman** [comment]
已修正，請 @kaojane 幫忙看看

**Comment by kaojane** [comment]
OK了 感謝
