### ISSUE TITLE
贊助商/講者 下架狀態關閉表單

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#107]
於後台設定狀態為"下架"時，可同步關閉前台表單不予進入編輯
(可顯示"目前表單已關閉")

**Comment by hashman** [comment]
這個 issue 需要前後端一起處理，目前後端沒有針對 type 進行過濾，這邊麻煩幫忙加上去，這個請 @xwang0929 幫忙處理贊助商與講者，前端的部分再請 @Tzuhui 幫忙

麻煩兩位了

**Comment by hashman** [comment]
推送完成，請 @kaojane 幫忙確認，謝謝

**Comment by kaojane** [comment]
OK!
