### ISSUE TITLE
贊助商 部分欄位改為非必填

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#110]
1.Logo 
2.產品或服務照片 
3.場間投影片
4.電子看板
上述可能會分次編修無法一次湊齊，
故改成非必填選項(前端要同步把*移除)

**Comment by hashman** [comment]
這個請 @FWcloud916 與 @Tzuhui 幫忙，謝謝

**Comment by hashman** [comment]
請 @kaojane 幫忙 testing 環境驗證一下，謝謝

**Comment by kaojane** [comment]
OK了 感恩
