### ISSUE TITLE
[贊助商前台] 檔案上傳錯誤訊息

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#126]
進階贊助商資料處出現上傳檔案錯誤(演講廳旗幟)
https://i.imgur.com/pPFPpJP.png
不曉得是不是圖檔容量有限制問題？

**Comment by hashman** [comment]
是檔案大小的問題， php.ini 設定的預設值為 2M 我這邊暫時先放寬到 5M 只是這個放空不可以沒有極限，還是需要限制的，所以如果可以的話還是需要確認贊助商 / 講師他們所上傳的素材，大小多少是合理的

**Comment by hashman** [comment]
錯誤訊息的部分已經有做優化了，剩下的我跟 Maintainer 討論一下

**Comment by hashman** [comment]
跟 Maintainer 討論完，這邊的上限就是 20M 不會再增加了，其他的就用連結的方式來解決了，我先關票了
