### ISSUE TITLE
[贊助商前台] Server error

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#133]
截圖：http://prntscr.com/ow4ojf

表單：https://cms.mopcon.org/sponsor/form/d487b2b2-7bf1-4211-b431-14b978b4ac48
表單密碼：KAwrRfE9avxpHjnT8L2T

親測一下有可能是"公司簡介"或"產品及服務介紹"這個欄位
填入下述測試內容，會看到字數統計還在250字內，但送出會出現error訊息

"策略無限 致力於機器人理財平台及程式交易研究，以台指期 21 年超過 4 億筆 tick 大數據資料為基礎，架構策略開發回測系統，建立 Tick 級高速且精準的回測機制，並能界接 AI 決策訊號進行深度回測，使用多種 AI 演算法研發近兩百隻的智慧下單策略，並透過策略管理機制有效降低策略風暴比，並完善整體資金風險管理系統，希望打破一般大眾對期貨的印象，跳脫舊市場框架思維，充分運用人工智慧、大數據等科技，提升產品效能及使用者體驗，提供完善的機器人理財服務。"

(我也不確定是否字數導致，只是如果上述欄位隨便key個單字，表單倒可以正常送出。)

**Comment by hashman** [comment]
推上測試環境了，可以幫我試試看

**Comment by hashman** [comment]
這邊確認修復了，我就關掉了
