### ISSUE TITLE
[贊助商前台] 欄位名稱調整

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#140]
為加強贊助商理解各欄位用途，重新調整前端顯示的名稱
另於題目下方增加副標(小一字級 字體顏色較淡)作補充說明
文件：
https://docs.google.com/spreadsheets/d/1KHV9-Ei7gp57lvpyV604Dk838JtKZhcAnlU5cbqup04/edit#gid=0

**Comment by hashman** [comment]
這題請 @xwang0929 幫忙一下，謝謝

**Comment by xwang0929** [comment]
@kaojane 英文版不用嗎？

**Comment by kaojane** [comment]
@xwang0929 經詢問目前尚無使用外語的贊助商，故暫時可先做中文就好

**Comment by hashman** [comment]
推上去了請 @kaojane 看看，謝謝

**Comment by kaojane** [comment]
公司簡介 及 產品及服務介紹 的主標沒改到~

**Comment by xwang0929** [comment]
> 公司簡介 及 產品及服務介紹 的主標沒改到~

oops，我以為那是筆誤

**Comment by kaojane** [comment]
不好意思 再補充:

社群粉絲貼文搭配圖片 | 可為產品或服務照片(最多不超過4張)

謝謝

**Comment by kaojane** [comment]
補一個：
英文公司簡介 => 官網/APP贊助商頁面-英文簡介

**Comment by xwang0929** [comment]
@kaojane 
> 社群粉絲貼文搭配圖片 | 可為產品或服務照片(最多不超過4張)

是 "主標 | 副標" 還是整個主標換成這個？

**Comment by kaojane** [comment]
主標 | 副標 维持~只有差在後面補充最多不超過4張

**Comment by hashman** [comment]
這個 issue 與 #144 牴觸，麻煩確認一下

**Comment by kaojane** [comment]
社群粉絲貼文搭配圖片 | 可為產品或服務照片(最多不超過4張)
於本次推送後面那句(最多不超過4張)刪除

**Comment by xwang0929** [comment]
這邊的文字要繼續調整嗎？還是要併到 #144 一起處理？

**Comment by kaojane** [comment]
這邊文字是已經給贊助組看過沒問題了~
若#144還需要開發時間，建議分開處理這邊先推送
(社群粉絲貼文搭配圖片 那句副標改只有"可為產品或服務照片")

**Comment by hashman** [comment]
等候 CI 推送到 testing 上面

**Comment by hashman** [comment]
推送上 Production
