### ISSUE TITLE
[講者前/後台] 增加新表單狀態

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#141]
後台除原本待確認/已確認/已下架等狀態外增加增加新狀態【議程組已確認】
(僅可由後台手動修改)
此狀態情況下，前台表單可進入但無法編輯，
進入時於上方顯示提醒
「您的資料已由Mopcon確認完畢，僅供檢視，若須修改請聯繫議程組工作人員。」
並移除下方驗證與送出按鈕。

**Comment by hashman** [comment]
@kaojane 我在想狀態的名稱用「關閉前台修改」會不會比較直覺一點？

**Comment by hashman** [comment]
此外這題會請 @xwang0929 幫忙支援一下，請中哥關注一下，謝謝

**Comment by kaojane** [comment]
@hashman  「關閉前台修改」=>OK

**Comment by hashman** [comment]
請 @xwang0929 幫忙，謝謝

**Comment by hashman** [comment]
推上去了請 @kaojane 看看，謝謝

**Comment by kaojane** [comment]
OK 目前是只有上測試站嗎

**Comment by hashman** [comment]
> 測OK 目前是只有上測試站嗎

對的，等 confirm 才會 release

**Comment by kaojane** [comment]
那我這邊OK~~!
