### ISSUE TITLE
[贊助商前後台] 新增檔案上傳可填寫雲端硬碟連結

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#144]
前台於各項檔案上傳欄位後方加入選填連結欄位
提示文字:或提供雲端硬碟檔案連結 (適用檔案超過20M或2個以上檔案)
呈現範例
https://i.imgur.com/CHNQSMZ.jpg
目前有檔案上傳的題目:
◆企業 Logo
◆社群粉絲貼文搭配圖片
◆場間投影片廣告
◆電子看板
◆ICCK 大門口兩側廣告柱
◆報到處全版廣告空間 ( Truss 架廣告)
◆演講廳旗幟
◆主動線旗幟廣告
後台查看詳細頁，增加上述欄位文字輸入內容並可點選連結

增加欄位副標：
社群粉絲貼文搭配圖片 | 可為產品或服務照片(多檔案請使用雲端連結，最多不超過4張)

**Comment by xwang0929** [comment]
補充說明：
* 可以上傳的欄位除了圖檔也要能接受壓縮檔
* 上傳檔案不得超過 20M
* 另外開放直接輸入檔案連結，輸入連結或上傳檔案只能二選一

**Comment by hashman** [comment]
這個會請 @FWcloud916 幫忙處理

**Comment by kaojane** [comment]
測OK了 感恩~

**Comment by hashman** [comment]
推送上去了
