### ISSUE TITLE
[贊助商前台]增加圖檔支援度

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#149]
- ICCK 大門口兩側廣告柱
- 報到處全版廣告空間 ( Truss 架廣告)
- 演講廳旗幟
- 主動線旗幟廣告
上述這幾個欄位要支援.ai檔與.psd
感謝

**Comment by hashman** [comment]
「產品或服務照片」、「場間頭影片」、「電子看版」這些都不需要？

**Comment by kaojane** [comment]
目前收到的請求是上述幾個(主要是大圖輸出緣故)
若修改上不麻煩可以一併開放~感謝

**Comment by hashman** [comment]
請 @FWcloud916  今天先幫忙一下，謝謝

**Comment by hashman** [comment]
Deploy 上 testing 了，請 @kaojane 幫忙看看，謝謝

**Comment by hashman** [comment]
另外是也請 Jane 幫忙看看這個版本可否 Deploy 出去了，謝謝

**Comment by kaojane** [comment]
測試OK了，感謝
