### ISSUE TITLE
[講者前後台] 議程Tag修改

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#153]
因應議程組調整
Tag另增加Agile
http://prntscr.com/p19hdl

**Comment by hashman** [comment]
Hi @kaojane 不是很懂為什麼已經有 Agile / DevOps 的 Tag 還需要額外增加一個 agile 的 tag ，另外是這個 tag 的名稱有沒有錯誤？是 agile 還是 Agile ？謝謝

**Comment by kaojane** [comment]
sorry~因為是兩個人各自發來的，我沒發現重複所以混在一起了，我請議程組再確認一下

**Comment by kaojane** [comment]
更新需求為，新增一個Agile標籤，其他不動

**Comment by hashman** [comment]
@kaojane 我推送上 dev 了

**Comment by kaojane** [comment]
OK 看到了 可以上正式站~

**Comment by hashman** [comment]
推上去了
