### ISSUE TITLE
[講者 / 贊助商] 後台能支援完整匯出嗎

### ISSUE THREAD

**Issue by 3KNI** [MOPCON/Equipment-management-system#158]
不知道後台能不能支援完整匯出，不然如果想看到全部的列表還是得一頁一頁慢慢按 Orz

**Comment by hashman** [comment]
確實是個問題沒錯，這個請 @Tzuhui 幫忙，謝謝

**Comment by hashman** [comment]
我還有另外一個想法，如果沒有選擇就是完整匯出功能，這樣可能會比較直覺一點？

@kaojane 幫忙判斷一下，謝謝

**Comment by 3KNI** [comment]
我覺得大多時間應該都會選擇完整匯出xd 感覺這個方法不錯

**Comment by 3KNI** [comment]
感謝速速增加此 feature <(_ _)>
