### ISSUE TITLE
[講者 / 贊助商] 匯出功能被 \n 影響

### ISSUE THREAD

**Issue by hashman** [MOPCON/Equipment-management-system#161]
匯出的時候可以將一些特殊符號將他們濾掉，這樣才不會影響到匯出的結果

**Comment by hashman** [comment]
這樣好了， export 出來的資料改成 `\\n` 的格式，然後 converter 程式將 `\\n` 改為 `\n` 格式，你們覺得呢？

**Comment by FWcloud916** [comment]
`json_encode` 會編譯 `\n` 所以應該不要再轉換回來送出去的資料才能保留原來的格式
@hashman @xwang0929
