### ISSUE TITLE
EMS 講者表單加上標註

### ISSUE THREAD

**Issue by Tzuhui** [MOPCON/Equipment-management-system#203]
- 個人資料與議程資料標題旁加註：公開顯示於網站/APP / 行政資料加註：不公開
- 詳細參考整理的修改第 3 點：https://docs.google.com/document/d/1KRDnd-F3WY47O3ZPsne3cbAP54FzIEvOvku4_CzWBQo/edit

**Comment by Chi-Chi-Chi-Chita** [comment]
@Tzuhui 
英文版也需要放加註嗎？如果需要，麻煩提供英文翻譯，感謝。

**Comment by Tzuhui** [comment]
@Chi-Chi-Chi-Chita 
翻譯在這邊：
Public on website/App 公開於網站或App
Non public 不公開
