### ISSUE TITLE
[講者]EMS 講者表單、 api 調整

### ISSUE THREAD

**Issue by FWcloud916** [MOPCON/Equipment-management-system#205]
EMS 講者
- [ ] 授權項目調整
- [ ] 增加真實姓名 、 Email 、 手機號碼
- [ ] 講者 api 增加狀態篩選
- [ ] 檢查難易度選項後端是否需要調整

**Comment by FWcloud916** [comment]
>  授權項目調整

> 增加真實姓名 、 Email 、 手機號碼
這邊需要增加新的欄位來處理

**Comment by FWcloud916** [comment]
授權項目調整
原本只有 一個欄位 license
![image](https://user-images.githubusercontent.com/20121433/85851767-e6725a80-b7e1-11ea-82c2-3e0458e1fb72.png)

現在要將題目拆成兩題 所以後端的欄位也要調整

> (1)授予 MOPCON 演講時錄影，後製與上傳至公開線上影音平台之權利
> 選項：
> 是(預設)  
> 謝絕錄影，但接受工作人員文字紀錄。
> 若為是，再填(2)
> (2)授權方式 ( 個授權說明詳見https://cc.ocf.tw/)：
> 選項：
> 以 CC BY 3.0 姓名標示方式授權。(預設)
> 以 CC BY-SA 3.0 姓名標示-相同方式授權。
> 以 CC BY-NC 3.0 姓名標示-非商業性方式授權。

第二題維持使用 license 欄位
第一題另外新增一個欄位

**Comment by FWcloud916** [comment]
增加真實姓名 、 Email 、 手機號碼
要新增三個欄位去紀錄

**Comment by FWcloud916** [comment]
講者 api 增加狀態篩選
針對 speaker_status 欄位做篩選

**Comment by FWcloud916** [comment]
檢查難易度選項後端是否需要調整
前端會移除難易度的問題，當初是記錄在 level 欄位
麻煩協助調整後端會受影響的部分

**Comment by FWcloud916** [comment]
請 @unciax 幫忙

**Comment by unciax** [comment]
level 可以存 null，看起來檢核沒有判斷這個欄位，推估應該不會有影響
