### ISSUE TITLE
設計贊助商素材上傳頁面

### ISSUE THREAD

**Issue by hashman** [MOPCON/Equipment-management-system#54]
Ref Issue: https://github.com/MOPCON/MOPCON/issues/142

參考文件：https://docs.google.com/document/d/1vdx2N52TuFyNiZZ64fLH9C353QX5VBVWOEb5_FbT-Ug/edit

參考上方文件，設計給贊助商上傳素材之前端介面

**Comment by Tzuhui** [comment]
@hashman 因為贊助商素材上傳介面的 route 還沒有確定，所以我還沒有推上來
想請問是要等 route 問題解決再推，還是先把頁面推上來呢～？

**Comment by hashman** [comment]
> @hashman 因為贊助商素材上傳介面的 route 還沒有確定，所以我還沒有推上來
> 想請問是要等 route 問題解決再推，還是先把頁面推上來呢～？

可以參考 Mars 的這個 commit 先用測試的 route 上去，讓後端再改就好

**Comment by hashman** [comment]
Sprint 3 繼續努力，邀請 @FWcloud916 入場幫忙後端，謝謝

**Comment by hashman** [comment]
這個 issue 主要是前端介面設計，已經完成了，後續後端就改為 #79 進行追蹤

感謝幫忙
