### ISSUE TITLE
離開「訊息發送」頁面後，仍一直在跟 api 要資料

### ISSUE THREAD

**Issue by unciax** [MOPCON/Equipment-management-system#68]
## 功能路徑
頁面：Telegram Bot -> 訊息發送

## 問題描述
離開頁面後，仍一直在跟 api 要訊息清單
<img width="1065" alt="螢幕快照 2019-06-04 下午11 20 15" src="https://user-images.githubusercontent.com/3615031/58891623-73ea9480-871f-11e9-9bf4-1ccaaa441d51.png">

## 預期行為
離開頁面後不會再跟 api 要訊息清單

**Comment by puckwang** [comment]
@unciax 再看看有沒有問題

**Comment by unciax** [comment]
恢復正常了，謝謝。
