### ISSUE TITLE
講者上傳頁前台文字修正

### ISSUE THREAD

**Issue by kaojane** [MOPCON/Equipment-management-system#69]
修正處：
FinTech/Quant 改回 Quant

**Comment by hashman** [comment]
請 @Tzuhui 幫忙謝謝

**Comment by hsimao** [comment]
@hashman 
我拉取當前最新的進度下來，發現運行 php artisan serve 會報錯，無法正常運行
錯誤訊息如下，不知道要如何修正＠＠

<img width="703" alt="螢幕快照 2019-06-06 下午12 24 32" src="https://user-images.githubusercontent.com/32007780/59006947-05105700-8857-11e9-8a76-2d9389a13d7e.png">


現在我要退回，用舊版本開分支改完PR就好？
還是等問題確認完，在拉取最新版本後在開新分支PR這個 issues？

**Comment by puckwang** [comment]
> @hashman
> 我拉取當前最新的進度下來，發現運行 php artisan serve 會報錯，無法正常運行
> 錯誤訊息如下，不知道要如何修正＠＠
> 
> <img alt="螢幕快照 2019-06-06 下午12 24 32" width="703" src="https://user-images.githubusercontent.com/32007780/59006947-05105700-8857-11e9-8a76-2d9389a13d7e.png">
> 
> 現在我要退回，用舊版本開分支改完PR就好？
> 還是等問題確認完，在拉取最新版本後在開新分支PR這個 issues？

Maybe you can run `composer install` & `php artisan db:seed --class RolesAndPermissionsSeeder` to fix it.

**Comment by hashman** [comment]
感謝 @puckwang 幫忙回答， @hsimao 再試試看，有問題隨時提問

**Comment by hashman** [comment]
我剛剛發現我 assign 錯人了... 拍謝，已經推上測試環境囉，請 @kaojane 幫忙看看
