### ISSUE TITLE
使用 Markdown 格式撰寫 API Doc

### ISSUE THREAD

**Issue by puckwang** [MOPCON/Equipment-management-system#82]
目前看到 API 文件非使用 Markdown 格式，無法於 GIthub 直接查看。

請依參考格式修改已存在的文件，未來有新的文件也遵照這個格式。

參考格式：[https://gist.github.com/iros/3426278](https://gist.github.com/iros/3426278)

**Comment by hashman** [comment]
你是指 API Blueprint 的部分嗎？

**Comment by puckwang** [comment]
Yep

**Comment by hashman** [comment]
這題先說一下確實沒有先討論而由我這邊直接決定使用 API Blueprint 做為 API Document 的方案，會使用 API Blueprint 的原因如下

1. 生態系夠大，使用者夠多
2. 時間久
3. 背後有公司在支持
4. 穩定度不錯，幾年了都沒有更新 code 也沒有什麼人來反映問題 xDD

但使用 API Blueprint 會有個問題就是 render 的平台要用什麼？如果是 Markdown 可以直接在 Github 上面直接 preview 但 API Blueprint 並沒有這方面的方案，目前有兩個做法可以顯示

1. 直接使用 vscode 裝上 API Blueprint 的 plugin 來 preview ，缺點就是一定要本機瀏覽，無法隨時隨地可以看到
2. 把 compile 的流程放入 CI 中，然後 deploy 到某個 site 上，這樣就可以直接看到，但是就等於把這個 API Document public 出去了

分享一下要用什麼方式呈現都是沒關係的，重點在於大家願意維護且有共識才是最重要的，文件是活的，規定是死的 xD ，此外補充一下，這個 issue 討論完可以再 `README.md` or `CONTRIBUTE.md` 裡面將這個 guideline 寫上，方便後人知悉這個規定

**Comment by puckwang** [comment]
我可能沒有描述的很清楚..

我是希望這個專案不要去相依於任何 IDE，也就是任何人 Clone 下來只要裝好開發基本的東西就可以開發了，而不是為了這個專案還去裝對應的 IDE 甚至 OS。

當然如果目前的 API 文件的解決方案可以達到以上目的的話，我是覺得就可以用它。

**Comment by hashman** [comment]
cc @xwang0929

**Comment by dada8397** [comment]
我覺得要追求立即可讀性的話可以用 Markdown 格式
畢竟外人進到這個專案的門面就是我們的 README.md

**Comment by puckwang** [comment]
> 這題先說一下確實沒有先討論而由我這邊直接決定使用 API Blueprint 做為 API Document 的方案，會使用 API Blueprint 的原因如下
> 
> 1. 生態系夠大，使用者夠多
> 2. 時間久
> 3. 背後有公司在支持
> 4. 穩定度不錯，幾年了都沒有更新 code 也沒有什麼人來反映問題 xDD
> 
> 但使用 API Blueprint 會有個問題就是 render 的平台要用什麼？如果是 Markdown 可以直接在 Github 上面直接 preview 但 API Blueprint 並沒有這方面的方案，目前有兩個做法可以顯示
> 
> 1. 直接使用 vscode 裝上 API Blueprint 的 plugin 來 preview ，缺點就是一定要本機瀏覽，無法隨時隨地可以看到
> 2. 把 compile 的流程放入 CI 中，然後 deploy 到某個 site 上，這樣就可以直接看到，但是就等於把這個 API Document public 出去了
> 
> 分享一下要用什麼方式呈現都是沒關係的，重點在於大家願意維護且有共識才是最重要的，文件是活的，規定是死的 xD ，此外補充一下，這個 issue 討論完可以再 `README.md` or `CONTRIBUTE.md` 裡面將這個 guideline 寫上，方便後人知悉這個規定

`README.md` or `CONTRIBUTE.md`  這兩份文件確實需要再修改，目前還不完善，在這 issue 討論一下內容一次補齊他

**Comment by xwang0929** [comment]
我是第一次使用 API Blueprint，還蠻容易上手的，它的語法是 Markdown Syntax for Object Notation，並沒有綁定特定 OS 或 IDE，那個 vscode 的 extension 也是因為我懶得裝工具才去找的，[官網有列出很多相關工具](https://apiblueprint.org/tools.html)。

有疑慮的話可以把附檔名改成 .md，apib 的相關工具還是可以使用。個人是覺得 apib 產生出來的文件比較漂亮。

**Comment by hashman** [comment]
> 我是第一次使用 API Blueprint，還蠻容易上手的，它的語法是 Markdown Syntax for Object Notation，並沒有綁定特定 OS 或 IDE，那個 vscode 的 extension 也是因為我懶得裝工具才去找的，[官網有列出很多相關工具](https://apiblueprint.org/tools.html)。
> 
> 有疑慮的話可以把附檔名改成 .md，apib 的相關工具還是可以使用。個人是覺得 apib 產生出來的文件比較漂亮。

測試一下確實沒問題，還是可以用 Markdown 的格式留存，透過 aglio 或是 plugin 可以看到 render 後的 html 也沒問題

**Comment by puckwang** [comment]
> > 我是第一次使用 API Blueprint，還蠻容易上手的，它的語法是 Markdown Syntax for Object Notation，並沒有綁定特定 OS 或 IDE，那個 vscode 的 extension 也是因為我懶得裝工具才去找的，[官網有列出很多相關工具](https://apiblueprint.org/tools.html)。
> > 有疑慮的話可以把附檔名改成 .md，apib 的相關工具還是可以使用。個人是覺得 apib 產生出來的文件比較漂亮。
> 
> 測試一下確實沒問題，還是可以用 Markdown 的格式留存，透過 aglio 或是 plugin 可以看到 render 後的 html 也沒問題
> 
> 但說實話這個 Markdown 的 [preview](https://github.com/hashman/Equipment-management-system/blob/feature/test-format/doc/apiBluePrint/speaker.md) 真的眼睛是蠻痛的 xDD
> 
> 另外是也將 api blueprint 出來的[結果](https://htmlpreview.github.io/?https://raw.githubusercontent.com/hashman/Equipment-management-system/feature/test-format/output.html)貼給大家看看

這個 [preview](https://github.com/hashman/Equipment-management-system/blob/feature/test-format/doc/apiBluePrint/speaker.md) 我覺得真的不行....

**Comment by xwang0929** [comment]
針對 json 調了一下語法，看看[這樣](https://github.com/xwang0929/Equipment-management-system/blob/test/apib-to-md/doc/apiBluePrint/speaker.md)有沒有比較善待眼睛。

**Comment by hashman** [comment]
> 針對 json 調了一下語法，看看[這樣](https://github.com/xwang0929/Equipment-management-system/blob/test/apib-to-md/doc/apiBluePrint/speaker.md)有沒有比較善待眼睛。

JSON 好很多 @puckwang 你覺得呢？

**Comment by puckwang** [comment]
> > 針對 json 調了一下語法，看看[這樣](https://github.com/xwang0929/Equipment-management-system/blob/test/apib-to-md/doc/apiBluePrint/speaker.md)有沒有比較善待眼睛。
> 
> JSON 好很多 @puckwang 你覺得呢？

我是覺得只有 JSON 有變好，其他 @MOPCON/emscoremember 覺得如何？

我們要從未來會維護的人下去，或許會比較好。

有幾個選擇，先看看各位比較傾向哪個？
1. 就這樣 ❤️
2. 用 Markdown 🚀
3. 再找其他 👀

**Comment by hashman** [comment]
各有優劣，雖說 api blueprint 也是用類似 Markdown 的語法去寫，但終究不是 Markdown ，如果不是用 draft render 出來的結果來看，還是比較不直覺些沒錯，也分享一下 Open Source 文化有趣的地方就在於對於不同意見的情況下大家可以彼此交換想法，看到一些沒有看到的東西，願意對於文件的貢獻的開發者也是非常的難得可貴，這邊有個小建議就是那個 sample 有點久了，我們可以參考他走出我們的一個格式，有些東西我認為必要但是沒有在上面，後面可以在交換一下意見，最後我投下 Markdown

**Comment by hashman** [comment]
這個 issue 討論完了，我就關囉
